//---------------------------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated by T4Model template for T4 (https://github.com/linq2db/t4models).
//    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// </auto-generated>
//---------------------------------------------------------------------------------------------------
using System;
using System.Collections.Generic;
using System.Linq;

using LinqToDB;
using LinqToDB.Mapping;

namespace DataModels
{
	/// <summary>
	/// Database       : bazy
	/// Data Source    : 150.254.44.162
	/// Server Version : 5.7.20-log
	/// </summary>
	public partial class BazyDB : LinqToDB.Data.DataConnection
	{
		public ITable<Druzyna>                 Druzynas                { get { return this.GetTable<Druzyna>(); } }
		public ITable<Gracz>                   Graczs                  { get { return this.GetTable<Gracz>(); } }
		public ITable<KolejkaStatystykiGracza> KolejkaStatystykiGracza { get { return this.GetTable<KolejkaStatystykiGracza>(); } }
		public ITable<Mecz>                    Meczs                   { get { return this.GetTable<Mecz>(); } }
		public ITable<Osiagniecia>             Osiagniecias            { get { return this.GetTable<Osiagniecia>(); } }
		public ITable<StatystykiMeczu>         StatystykiMeczu         { get { return this.GetTable<StatystykiMeczu>(); } }
		public ITable<Udzial>                  Udzials                 { get { return this.GetTable<Udzial>(); } }
		public ITable<Widok>                   Widoks                  { get { return this.GetTable<Widok>(); } }
		public ITable<ZapisDoDruzyny>          ZapisDoDruzyny          { get { return this.GetTable<ZapisDoDruzyny>(); } }
		public ITable<Zdarzenie>               Zdarzenies              { get { return this.GetTable<Zdarzenie>(); } }

		public BazyDB()
		{
			InitDataContext();
		}

		public BazyDB(string configuration)
			: base(configuration)
		{
			InitDataContext();
		}

		partial void InitDataContext();
	}

	[Table("druzyna")]
	public partial class Druzyna
	{
		[Column("idDruzyny"),     PrimaryKey, NotNull] public int    IdDruzyny    { get; set; } // int(11)
		[Column("idMeczu"),                   NotNull] public int    IdMeczu      { get; set; } // int(11)
		[Column("Kolor_druzyny"),             NotNull] public string KolorDruzyny { get; set; } // varchar(5)

		#region Associations

		/// <summary>
		/// mecz_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdDruzyny", OtherKey="IdDruzynaRed", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Mecz> FKMeczs { get; set; }

		/// <summary>
		/// druzyna_ibfk_1
		/// </summary>
		[Association(ThisKey="IdMeczu", OtherKey="IdMecz", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="druzyna_ibfk_1", BackReferenceName="Druzynas")]
		public Mecz Mecz { get; set; }

		/// <summary>
		/// mecz_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="IdDruzyny", OtherKey="IdDruzynaBlue", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Mecz> Meczs { get; set; }

		/// <summary>
		/// zapis_do_druzyny_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="IdDruzyny", OtherKey="IdDruzyny", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ZapisDoDruzyny> ZapisDoDruzynies { get; set; }

		#endregion
	}

	[Table("gracz")]
	public partial class Gracz
	{
		[Column("idGracz"), PrimaryKey,  NotNull] public int       IdGracz         { get; set; } // int(11)
		[Column(),                       NotNull] public string    Nick            { get; set; } // varchar(30)
		[Column(),             Nullable         ] public string    SteamID         { get; set; } // varchar(45)
		[Column(),             Nullable         ] public string    NazwaKontaWGrze { get; set; } // varchar(45)
		[Column(),             Nullable         ] public DateTime? DataDolaczenia  { get; set; } // datetime

		#region Associations

		/// <summary>
		/// kolejka_statystyki_gracza_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdGracz", OtherKey="IdGracza", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<KolejkaStatystykiGracza> KolejkaStatystykiGraczas { get; set; }

		/// <summary>
		/// osiagniecia_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdGracz", OtherKey="IdGracza", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Osiagniecia> Osiagniecias { get; set; }

		/// <summary>
		/// udzial_ibfk_2_BackReference
		/// </summary>
		[Association(ThisKey="IdGracz", OtherKey="IdGracza", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Udzial> Udzials { get; set; }

		/// <summary>
		/// zapis_do_druzyny_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdGracz", OtherKey="IdGracza", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<ZapisDoDruzyny> ZapisDoDruzynies { get; set; }

		#endregion
	}

	[Table("kolejka_statystyki_gracza")]
	public partial class KolejkaStatystykiGracza
	{
		[Column("idKolejka_Statystyki_Gracza"), PrimaryKey,  NotNull] public int    IdKolejkaStatystykiGracza { get; set; } // int(11)
		[Column(),                                           NotNull] public string TypKolejki                { get; set; } // varchar(3)
		[Column("idGracza"),                                 NotNull] public int    IdGracza                  { get; set; } // int(11)
		[Column(),                                           NotNull] public int    ELO                       { get; set; } // int(11)
		[Column(),                                 Nullable         ] public float? Winrate                   { get; set; } // float
		[Column(),                                 Nullable         ] public float? KDA                       { get; set; } // float
		[Column(),                                 Nullable         ] public int?   Kills                     { get; set; } // int(11)
		[Column(),                                 Nullable         ] public int?   Deaths                    { get; set; } // int(11)
		[Column(),                                 Nullable         ] public int?   Assists                   { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// kolejka_statystyki_gracza_ibfk_1
		/// </summary>
		[Association(ThisKey="IdGracza", OtherKey="IdGracz", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="kolejka_statystyki_gracza_ibfk_1", BackReferenceName="KolejkaStatystykiGraczas")]
		public Gracz Gracz { get; set; }

		#endregion
	}

	[Table("mecz")]
	public partial class Mecz
	{
		[Column("idMecz"),             PrimaryKey,  NotNull] public int      IdMecz            { get; set; } // int(11)
		[Column("datameczu"),                       NotNull] public DateTime Datameczu         { get; set; } // datetime
		[Column("tryb"),                            NotNull] public string   Tryb              { get; set; } // varchar(45)
		[Column("idDruzynaRed"),                    NotNull] public int      IdDruzynaRed      { get; set; } // int(11)
		[Column("idDruzynaBlue"),                   NotNull] public int      IdDruzynaBlue     { get; set; } // int(11)
		[Column(),                                  NotNull] public string   Wynik             { get; set; } // varchar(5)
		[Column("idStatystyki_Meczu"),    Nullable         ] public int?     IdStatystykiMeczu { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// mecz_ibfk_2
		/// </summary>
		[Association(ThisKey="IdDruzynaBlue", OtherKey="IdDruzyny", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="mecz_ibfk_2", BackReferenceName="Meczs")]
		public Druzyna Druzyna { get; set; }

		/// <summary>
		/// druzyna_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdMecz", OtherKey="IdMeczu", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Druzyna> Druzynas { get; set; }

		/// <summary>
		/// mecz_ibfk_1
		/// </summary>
		[Association(ThisKey="IdDruzynaRed", OtherKey="IdDruzyny", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="mecz_ibfk_1", BackReferenceName="FKMeczs")]
		public Druzyna FKDruzyna { get; set; }

		/// <summary>
		/// mecz_ibfk_3
		/// </summary>
		[Association(ThisKey="IdStatystykiMeczu", OtherKey="IdStatystykiMeczu", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="mecz_ibfk_3", BackReferenceName="Meczs")]
		public StatystykiMeczu StatystykiMeczu { get; set; }

		/// <summary>
		/// statystyki_meczu_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdMecz", OtherKey="IdMeczu", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<StatystykiMeczu> StatystykiMeczus { get; set; }

		/// <summary>
		/// zdarzenie_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdMecz", OtherKey="IdMeczu", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Zdarzenie> Zdarzenies { get; set; }

		#endregion
	}

	[Table("osiagniecia")]
	public partial class Osiagniecia
	{
		[Column("idOsiagniecia"),      PrimaryKey, Identity] public int    IdOsiagniecia     { get; set; } // int(11)
		[Column("idGracza"),           NotNull             ] public int    IdGracza          { get; set; } // int(11)
		[Column("rodzaj_osiagniecia"), NotNull             ] public string RodzajOsiagniecia { get; set; } // varchar(45)

		#region Associations

		/// <summary>
		/// osiagniecia_ibfk_1
		/// </summary>
		[Association(ThisKey="IdGracza", OtherKey="IdGracz", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="osiagniecia_ibfk_1", BackReferenceName="Osiagniecias")]
		public Gracz Gracz { get; set; }

		#endregion
	}

	[Table("statystyki_meczu")]
	public partial class StatystykiMeczu
	{
		[Column("idStatystyki_Meczu"), PrimaryKey, NotNull] public int IdStatystykiMeczu { get; set; } // int(11)
		[Column("czas"),                           NotNull] public int Czas              { get; set; } // int(11)
		[Column("idMeczu"),                        NotNull] public int IdMeczu           { get; set; } // int(11)
		[Column(),                                 NotNull] public int ZabojstwaRed      { get; set; } // int(11)
		[Column(),                                 NotNull] public int ZabojstwaBlue     { get; set; } // int(11)
		[Column(),                                 NotNull] public int AsystyRed         { get; set; } // int(11)
		[Column(),                                 NotNull] public int AsystyBlue        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// statystyki_meczu_ibfk_1
		/// </summary>
		[Association(ThisKey="IdMeczu", OtherKey="IdMecz", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="statystyki_meczu_ibfk_1", BackReferenceName="StatystykiMeczus")]
		public Mecz Mecz { get; set; }

		/// <summary>
		/// mecz_ibfk_3_BackReference
		/// </summary>
		[Association(ThisKey="IdStatystykiMeczu", OtherKey="IdStatystykiMeczu", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Mecz> Meczs { get; set; }

		#endregion
	}

	[Table("udzial")]
	public partial class Udzial
	{
		[Column("idUdzial"),    PrimaryKey, NotNull] public int    IdUdzial    { get; set; } // int(11)
		[Column("idZdarzenie"),             NotNull] public int    IdZdarzenie { get; set; } // int(11)
		[Column("idGracza"),                NotNull] public int    IdGracza    { get; set; } // int(11)
		[Column(),                          NotNull] public string Rola        { get; set; } // varchar(5)

		#region Associations

		/// <summary>
		/// udzial_ibfk_2
		/// </summary>
		[Association(ThisKey="IdGracza", OtherKey="IdGracz", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="udzial_ibfk_2", BackReferenceName="Udzials")]
		public Gracz Gracz { get; set; }

		/// <summary>
		/// udzial_ibfk_1
		/// </summary>
		[Association(ThisKey="IdZdarzenie", OtherKey="IdZdarzenie", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="udzial_ibfk_1", BackReferenceName="Udzials")]
		public Zdarzenie Zdarzenie { get; set; }

		#endregion
	}

	[Table("widok", IsView=true)]
	public partial class Widok
	{
		[Column, NotNull] public long GraczeCS  { get; set; } // bigint(21)
		[Column, NotNull] public long GraczeLOL { get; set; } // bigint(21)
	}

	[Table("zapis_do_druzyny")]
	public partial class ZapisDoDruzyny
	{
		[Column("idZapis_do_druzyny"), PrimaryKey,  NotNull] public int  IdZapisDoDruzyny { get; set; } // int(11)
		[Column("idGracza"),              Nullable         ] public int? IdGracza         { get; set; } // int(11)
		[Column("idDruzyny"),             Nullable         ] public int? IdDruzyny        { get; set; } // int(11)

		#region Associations

		/// <summary>
		/// zapis_do_druzyny_ibfk_2
		/// </summary>
		[Association(ThisKey="IdDruzyny", OtherKey="IdDruzyny", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="zapis_do_druzyny_ibfk_2", BackReferenceName="ZapisDoDruzynies")]
		public Druzyna Druzyna { get; set; }

		/// <summary>
		/// zapis_do_druzyny_ibfk_1
		/// </summary>
		[Association(ThisKey="IdGracza", OtherKey="IdGracz", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="zapis_do_druzyny_ibfk_1", BackReferenceName="ZapisDoDruzynies")]
		public Gracz Gracz { get; set; }

		#endregion
	}

	[Table("zdarzenie")]
	public partial class Zdarzenie
	{
		[Column("idZdarzenie"),      PrimaryKey,  NotNull] public int    IdZdarzenie     { get; set; } // int(11)
		[Column("idMeczu"),             Nullable         ] public int?   IdMeczu         { get; set; } // int(11)
		[Column("rodzaj_zdarzenia"),    Nullable         ] public string RodzajZdarzenia { get; set; } // varchar(10)

		#region Associations

		/// <summary>
		/// zdarzenie_ibfk_1
		/// </summary>
		[Association(ThisKey="IdMeczu", OtherKey="IdMecz", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="zdarzenie_ibfk_1", BackReferenceName="Zdarzenies")]
		public Mecz Mecz { get; set; }

		/// <summary>
		/// udzial_ibfk_1_BackReference
		/// </summary>
		[Association(ThisKey="IdZdarzenie", OtherKey="IdZdarzenie", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Udzial> Udzials { get; set; }

		#endregion
	}

	public static partial class TableExtensions
	{
		public static Druzyna Find(this ITable<Druzyna> table, int IdDruzyny)
		{
			return table.FirstOrDefault(t =>
				t.IdDruzyny == IdDruzyny);
		}

		public static Gracz Find(this ITable<Gracz> table, int IdGracz)
		{
			return table.FirstOrDefault(t =>
				t.IdGracz == IdGracz);
		}

		public static KolejkaStatystykiGracza Find(this ITable<KolejkaStatystykiGracza> table, int IdKolejkaStatystykiGracza)
		{
			return table.FirstOrDefault(t =>
				t.IdKolejkaStatystykiGracza == IdKolejkaStatystykiGracza);
		}

		public static Mecz Find(this ITable<Mecz> table, int IdMecz)
		{
			return table.FirstOrDefault(t =>
				t.IdMecz == IdMecz);
		}

		public static Osiagniecia Find(this ITable<Osiagniecia> table, int IdOsiagniecia)
		{
			return table.FirstOrDefault(t =>
				t.IdOsiagniecia == IdOsiagniecia);
		}

		public static StatystykiMeczu Find(this ITable<StatystykiMeczu> table, int IdStatystykiMeczu)
		{
			return table.FirstOrDefault(t =>
				t.IdStatystykiMeczu == IdStatystykiMeczu);
		}

		public static Udzial Find(this ITable<Udzial> table, int IdUdzial)
		{
			return table.FirstOrDefault(t =>
				t.IdUdzial == IdUdzial);
		}

		public static ZapisDoDruzyny Find(this ITable<ZapisDoDruzyny> table, int IdZapisDoDruzyny)
		{
			return table.FirstOrDefault(t =>
				t.IdZapisDoDruzyny == IdZapisDoDruzyny);
		}

		public static Zdarzenie Find(this ITable<Zdarzenie> table, int IdZdarzenie)
		{
			return table.FirstOrDefault(t =>
				t.IdZdarzenie == IdZdarzenie);
		}
	}
}
